### ISSUE TITLE
如果将defaultValue中选择的值，放到右侧选中列表中

### ISSUE THREAD

**Issue by caosw199509** [Herozzq/element-tree-transfer-pro#3]
<img width="820" alt="image" src="https://github.com/Herozzq/element-tree-transfer-pro/assets/52447864/12ef8add-5751-4a39-a5aa-e27ae1d52757">
如标题，现在打开组件时存在默认值，需要将默认选中的值能够在右侧列表中展示。
麻烦大佬予以解答🙏

**Comment by Herozzq** [comment]
参考我的代码案例
mounted() {
            this.defaultValue = ["1-2"]
 },
我的演示demo中默认值就是直接在右侧框展示出来的

**Comment by daydayup001001** [comment]
如果将这个穿梭框放在弹层内，可以用 this.$nextTick(() => { });函数
比如：this.$nextTick(() => {this.defaultValue = ["1-2"] });
