### ISSUE TITLE
标准数据格式

### ISSUE THREAD

**Issue by daydayup001001** [Herozzq/element-tree-transfer-pro#5]
根据示例给出的数据格式如下：
  const tree = [{
            label: "A部门",
            id: "1",
            children: [{
                    label: "小明",
                    children: [],
                    id: "1-1",
                },
                {
                    label: "小红",
                    children: [],
                    id: "1-2",
                },
                {
                    label: "小刚",
                    children: [],
                    id: "1-3",
                },
            ],
        },
        {
            label: "B部门",
            id: "2",
            children: [{
                    label: "小王",
                    children: [],
                    id: "2-1",
                },
                {
                    label: "小李",
                    children: [],
                    id: "2-2",
                },
                {
                    label: "小朱",
                    children: [],
                    id: "2-3",
                },
            ],
        },
    ]
    这里每项都有一个children: []，我改进了一下，可以去掉children: []同时不会报错，望采纳：
    
![解决二](https://github.com/Herozzq/element-tree-transfer-pro/assets/93184750/c375fd58-77d2-4aac-a785-66e7257d5a9d)

**Comment by daydayup001001** [comment]
还要MD中
  import treeTransfer from 'element-mini-tree-transfer'部分
  应该是
 import treeTransfer from 'element-tree-transfer-pro‘

**Comment by daydayup001001** [comment]
以及源码中openAll参数是如下
    // 是否展开所有节点
    openAll: {
      type: Boolean,
      default: true,
    },
    与MD文档中写的是默认false

**Comment by Herozzq** [comment]
收到，感谢反馈，近期会抽时间优化

**Comment by Herozzq** [comment]
vue2的.vue文件中不支持?.的写法，其余反馈问题都已优化
