### ISSUE TITLE
使用bug

### ISSUE THREAD

**Issue by fm162336** [Herozzq/element-tree-transfer-pro#6]
我在使用的时候发现两个bug，在is-radio=true，father-choose=false的时候，会报错，无法正常使用；当is-radio=true，father-choose=true的时候，选择了一个节点传到右边后，再将右边的节点返回到左侧，会出现只有刚刚选择的节点是可选的，其他节点都无法选择。
![1697530419776](https://github.com/Herozzq/element-tree-transfer-pro/assets/40163561/f37f6a7f-59d3-409a-ab93-fde1af434aee)

**Comment by Herozzq** [comment]
近期有空会看一下

**Comment by Herozzq** [comment]
问题已修复，报错是你没传默认的children导致的，新版已经兼容了

**Comment by Herozzq** [comment]
问题已修复，报错是你没传默认的children导致的，新版已经兼容了
